use std::collections::BTreeMap;

use chrono::{DateTime, Utc};
use crate::Entity;
use crate::core::Handle;
use crate::core::config::SandboxLimits;
use crate::policy::sandbox::SandboxPolicy;
use serde::{Deserialize, Serialize};
use surrealdb::types::SurrealValue;

#[derive(Debug, Clone, Serialize, Deserialize, SurrealValue, Entity)]
#[surreal(crate = "surrealdb::types")]
#[entity(table = "agent")]
pub struct Agent {
    pub id: String,
    pub user_id: String,
    pub handle: Handle,
    pub name: String,
    pub description: String,
    pub model_group: String,
    pub enabled: bool,
    #[serde(default)]
    pub sandbox_limits: Option<SandboxLimits>,
    #[serde(default)]
    pub max_concurrent_tasks: Option<u32>,
    #[serde(default)]
    pub skills: Option<Vec<String>>,
    #[serde(default)]
    pub avatar: Option<String>,
    #[serde(default)]
    pub identity: BTreeMap<String, String>,
    #[serde(default)]
    pub prompt: Option<String>,
    pub heartbeat_interval: Option<u64>,
    pub next_heartbeat_at: Option<DateTime<Utc>>,
    pub heartbeat_chat_id: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Deserialize)]
pub struct CreateAgentRequest {
    pub id: Option<String>,
    #[serde(default)]
    pub handle: Option<String>,
    pub name: String,
    pub description: String,
    pub model_group: Option<String>,
    pub tools: Option<Vec<String>>,
    pub skills: Option<Vec<String>>,
    #[serde(default)]
    pub sandbox_policy: Option<SandboxPolicy>,
    #[serde(default)]
    pub sandbox_limits: Option<SandboxLimits>,
}

#[derive(Debug, Default, Deserialize, bon::Builder)]
pub struct UpdateAgentRequest {
    pub name: Option<String>,
    pub description: Option<String>,
    pub model_group: Option<String>,
    pub enabled: Option<bool>,
    pub tools: Option<Vec<String>>,
    pub skills: Option<Vec<String>>,
    /// `None` leaves existing policies untouched; `Some(default())` re-reconciles to empty.
    #[serde(default)]
    pub sandbox_policy: Option<SandboxPolicy>,
    #[serde(default)]
    pub sandbox_limits: Option<SandboxLimits>,
    pub prompt: Option<String>,
    pub identity: Option<BTreeMap<String, String>>,
}

#[derive(Debug, Serialize)]
pub struct AgentResponse {
    pub id: String,
    pub handle: Handle,
    pub name: String,
    pub description: String,
    pub model_group: String,
    /// API-only view of what `model_group` resolves to right now (model_ref +
    /// full catalog entry). Populated by the route layer via
    /// `provider_registry` + `model_catalog`; never persisted on `Agent`.
    /// `None` when the group name can't be resolved (config drift, agent
    /// referencing a removed group).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<Model>,
    pub enabled: bool,
    pub tools: Vec<String>,
    pub skills: Option<Vec<String>>,
    pub sandbox_policy: SandboxPolicy,
    pub sandbox_limits: Option<SandboxLimits>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<String>,
    pub identity: BTreeMap<String, String>,
    pub prompt: Option<String>,
    pub default_prompt: String,
    pub is_builtin: bool,
    pub chat_count: u64,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Serialize)]
pub struct Model {
    pub provider: String,
    pub model_id: String,
    /// Resolved context window for the model group: config override wins,
    /// otherwise catalog `max_input_tokens`, otherwise `DEFAULT_CONTEXT_WINDOW`.
    pub context_window: usize,
    #[serde(skip_serializing_if = "Option::is_none", flatten)]
    pub entry: Option<crate::inference::metadata::ModelEntry>,
}

// Generated by `build.rs` from `resources/agents/` directory names.
include!(concat!(env!("OUT_DIR"), "/builtin_handles.rs"));

impl AgentResponse {
    pub fn from_agent(agent: Agent, tools: Vec<String>, sandbox_policy: SandboxPolicy) -> Self {
        let is_builtin = BUILTIN_HANDLES.contains(&agent.handle);
        Self {
            id: agent.id,
            handle: agent.handle,
            name: agent.name,
            description: agent.description,
            model_group: agent.model_group,
            model: None,
            enabled: agent.enabled,
            tools,
            skills: agent.skills,
            sandbox_policy,
            sandbox_limits: agent.sandbox_limits,
            avatar_url: None,
            identity: agent.identity,
            prompt: agent.prompt,
            default_prompt: String::new(),
            is_builtin,
            chat_count: 0,
            created_at: agent.created_at,
            updated_at: agent.updated_at,
        }
    }
}

