apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frona

resources:
  - frona-pvc.yaml
  - frona-deployment.yaml
  - frona-service.yaml
  - searxng-configmap.yaml
  - frona-servicemonitor.yaml
